name: Pull Request Notifications

on:
  pull_request_target:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  notify_pr_open:
    # Only run this job for pull_request_target events
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"<@&1440523825782587414> a PR requires attention: \n${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}\"}" \
               "$WEBHOOK_URL"
               
  notify_pr_approved:
    # Only run for approval reviews
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"<@&1440523825782587414> a PR has been approved: \n${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}\"}" \
               "$WEBHOOK_URL"
