name: Pull Request Notification

on:
  pull_request_target:
    types: [opened, reopened, closed, review_requested, review_request_removed]

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        env:
          WEBHOOK_URL: ${{ secrets.TEST_DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"PR: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}\"}" \
               "$WEBHOOK_URL"
