name: Pull Request Notification

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        uses: leticiamantovani/custom-github-actions@main
        with:
          service: 'discord'
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_url: ${{ github.event.pull_request.html_url }}
          pr_action: ${{ github.event.action }}
          pr_author: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.repository }}
