name: Pull Request Notification

on:
  pull_request_target:
    types: [opened, reopened, closed, review_requested, review_request_removed]

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Discord
        uses: leticiamantovani/pull-request-notifier@v1.0.0
        with:
          service: 'discord'
          webhook_url: ${{ secrets.TEST_DISCORD_WEBHOOK_URL }}
